### ISSUE TITLE
GET /generate/ is not an ASCII text

### ISSUE THREAD

**Issue by vmurashev** [Lukasa/mkcert#10]
Could you please provide API to fetch cadata with comments removed ?
Some comments in downloaded file is not an ASCII text.
I understand that generally this is not a problem, but as for me I can't pass content of generated file into python module pycurl:
```
# cadata - string with content of downloaded file
c = pycurl.Curl()
c.set_ca_certs(cadata)
```
ful example - https://github.com/pycurl/pycurl/blob/master/tests/cadata_test.py
pycurl.set_ca_certs (this method appeared in pycurl  since version 7.43.0.1)

**Comment by Lukasa** [comment]
Just pipe it through `grep -v`: `curl https://mkcert.org/generate/ | grep -v "^#"`.
