### ISSUE TITLE
GET https://mkcert.org/labels/ ==> 404

### ISSUE THREAD

**Issue by DinoChiesa** [Lukasa/mkcert#12]
This isn't a bug in the mkcert.org service code, but rather a report of service outage in the https://mkcert.org API.

```$ curl -i  https://mkcert.org/labels/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Caddy
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Clacks-Overhead: GNU Terry Pratchett
X-Content-Type-Options: nosniff
Date: Fri, 06 Dec 2019 03:38:28 GMT
Content-Length: 14

404 Not Found
```

This is the documented interface.  I looked in the code and the code still seems to have the logic that responds to this. And it works as advertised when I download it and run it from my machine.

**Comment by Lukasa** [comment]
Interesting, that’s a weird failure mode. I’ll dig into this and see what I see.

**Comment by Lukasa** [comment]
Resolved: a misconfiguration in the reverse proxy caused the issue. Should be good now, thanks for letting me know!
