### ISSUE TITLE
CKA_NSS_SERVER_DISTRUST_AFTER is not handled properly

### ISSUE THREAD

**Issue by AGWA** [Lukasa/mkcert#19]
When parsing certdata.txt, mkcert excludes roots whose `CKA_NSS_SERVER_DISTRUST_AFTER` time is [after the current time](https://github.com/Lukasa/mkcert/blob/2f8a725f29d6d5d20e7981d0cdb9752ffdace2bf/certs/convert_mozilla_certdata.go#L275).

This is incorrect behavior. `CKA_NSS_SERVER_DISTRUST_AFTER` is supposed to be compared against the leaf certificate's NotBefore time, not the current time:

> If a builtin certificate has a CKA_NSS_SERVER_DISTRUST_AFTER timestamp before the SCT or NotBefore date of a certificate that builtin issued, then clients can elect not to trust it.

[Source](https://nss-crypto.org/reference/security/nss/legacy/nss_releases/nss_3.53_release_notes/index.html)

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1618404 and https://bugzilla.mozilla.org/show_bug.cgi?id=1621159

[Mozilla intends](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/jCvkhBjg9Yw/m/dzO2v1AtAQAJ) to set the `CKA_NSS_SERVER_DISTRUST_AFTER` date of Entrust roots to November 30, 2024. mkcert's current behavior will cause consumers of mkcert to reject Entrust certificates that Firefox would have accepted, causing breakage that Mozilla did not intend.

Instead, mkcert should just ignore the `CKA_NSS_SERVER_DISTRUST_AFTER` date.  Although this would cause consumers of mkcert to accept certificates that Firefox would have rejected, in practice this is not any less secure than Firefox.  This is because roots with a `CKA_NSS_SERVER_DISTRUST_AFTER` date still have the ability to issue new certificates that are accepted by Firefox, by simply backdating the certificate's NotBefore date.  The point of `CKA_NSS_SERVER_DISTRUST_AFTER` is not to provide security from an untrustworthy root, but to [gracefully sunset trust in a root](https://medium.com/@sleevi_/path-building-vs-path-verifying-the-chain-of-pain-9fbab861d7d6#2bf8).  When Mozilla adds `CKA_NSS_SERVER_DISTRUST_AFTER` to a root, they're not saying that certificates issued after that date are untrustworthy.  Instead, they are saying that they would like to remove the root at some point in the future.  Combined with enforcement of the 398 day maximum certificate lifetime, `CKA_NSS_SERVER_DISTRUST_AFTER` ensures that all certificates issued by a root are expired 398 days after the `CKA_NSS_SERVER_DISTRUST_AFTER` date, allowing for the root's removal without breakage. Consequentially, it is appropriate for mkcert to ignore `CKA_NSS_SERVER_DISTRUST_AFTER` and wait for Mozilla to fully remove the root.

**Comment by alex** [comment]
Thanks Andrew. https://github.com/Lukasa/mkcert/pull/20 should address this.

**Comment by AGWA** [comment]
Nice idea to exclude the root 398 days after the Distrust After!
